name: プロジェクト課題
description: プロジェクト推進上の課題・未決定事項に関するissue
body:
  - type: textarea
    id: contents
    attributes:
      label: 課題内容
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: やること、完了条件
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: 備考
