name: 機能追加・変更
description: 機能追加・変更に関するissue
body:
  - type: textarea
    id: background
    attributes:
      label: 背景
      description: どのような課題を抱えてissueを立てたのか、経緯や前提を記載してください。
    validations:
      required: true
  - type: textarea
    id: tobe
    attributes:
      label: あるべき状態
      description: どうなっているべきなのかの完了条件を記載してください。
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: やること
      description: このissueで取り組むことを記載してください。
    validations:
      required: true
  - type: textarea
    id: remarks
    attributes:
      label: 備考
